apiVersion: v1
kind: Pod
metadata:
  name: kubernetes4oe-db
  labels:
    name: kubernetes4oe-db
    type: db
spec:
  containers:
  - name: sports2020-db
    image: eu.gcr.io/kubernetes4oe/sports2020-db
    ports:
      - containerPort: 10000
        name: minus-s
        protocol: TCP
      - containerPort: 10010
        name: server-1
        protocol: TCP
      - containerPort: 10011
        name: server-2
        protocol: TCP
      - containerPort: 10012
        name: server-3
        protocol: TCP
