apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubernetes4oe
    component: db
    name: kubernetes4oe-db
  name: kubernetes4oe-db
  namespace: default
spec:
  ports:
  - name: port-1
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: port-2
    port: 10010
    protocol: TCP
    targetPort: 10010
  - name: port-3
    port: 10011
    protocol: TCP
    targetPort: 10011
  - name: port-4
    port: 10012
    protocol: TCP
    targetPort: 10012
  selector:
    name: kubernetes4oe-db
    type: db
  sessionAffinity: None
  type: ClusterIP
