apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kubernetes4oe-pas
spec:
  replicas: 3  # tells deployment to run 1 pods matching the template
  selector:
    matchLabels:
      app: kubernetes4oe
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubernetes4oe
        component: appserver
    spec:
      containers:
      - name: kubernetes4oe-pas
        image: eu.gcr.io/kubernetes4oe/kubernetes4oe-pas
        resources:
          requests: 
            cpu: "125m"
            memory: "384Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
        ports:
        - containerPort: 8810
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes4oe-pas-service
  namespace: default
spec:
  # externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8810
    # nodePort: 30321
  selector:
    app: kubernetes4oe
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: "34.91.118.138"
  